# command history: user.history_toggle()
history show: user.history_toggle()
history clear: user.history_clear()
# command history clear: user.history_clear()
# command history less: user.history_less()
# command history more: user.history_more()
